chain:
    bech32_prefix: evmos
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - slashing
        - distribution
        - upgrade
        - actions
        - inflation
        - storage
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: localhost:9090
            insecure: true
parsing:
    workers: 1
    start_height: 1
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
database:
    url: postgresql://postgres:postgrespassword@localhost:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
    ssl_mode_enable: "false"
    ssl_root_cert: ""
    ssl_cert: ""
    ssl_key: ""
logging:
    level: debug
    format: text
actions:
    host: 0.0.0.0
    port: 3000
